export {
  LOCAL_STORAGE_ERROR_CODES,
  createCapacityExceededError,
  createDeviceKeyMissingError,
  createInvalidArgumentError,
  createInvalidDeviceKeyError,
  createObjectNotFoundError,
  createPersistenceUnavailableError,
  createQuotaUnavailableError,
  createStorageUnavailableError,
  createStorageWriteFailedError,
  type CapacityExceededError,
  type CapacityExceededReason,
  type DeviceKeyMissingError,
  type InvalidArgumentError,
  type InvalidArgumentReason,
  type InvalidDeviceKeyError,
  type LocalStorageError,
  type LocalStorageErrorCode,
  type ObjectNotFoundError,
  type ObjectNotFoundReason,
  type PersistenceUnavailableError,
  type PersistenceUnavailableReason,
  type QuotaUnavailableError,
  type QuotaUnavailableReason,
  type StorageUnavailableError,
  type StorageUnavailableReason,
  type StorageWriteFailedError,
  type WriteFailedReason,
} from "./errors.js";

export {
  DEVICE_KEY_DB_NAME,
  DEVICE_KEY_DB_VERSION,
  DEVICE_KEY_RECORD_ID,
  DEVICE_KEY_STORE_NAME,
} from "./device-key-store.js";

export {
  clearDeviceKey,
  ensureDeviceKey,
  generateDeviceKey,
  hasDeviceKey,
  isPersisted,
  openDeviceBound,
  requestPersistentStorage,
  requireStoredDeviceKey,
  sealDeviceBound,
  type DeviceKeyHandle,
  type OpenDeviceBoundInput,
  type SealDeviceBoundInput,
} from "./device-key.js";

export {
  PROJECT_BACKUP_PAYLOAD_LIMIT_BYTES,
  PROJECT_ENVELOPE_CHUNK_BYTES,
  PROJECT_ENVELOPE_CHUNK_LENGTH_FIELD_BYTES,
  PROJECT_ENVELOPE_CHUNK_TAG_BYTES,
  PROJECT_ENVELOPE_HEADER_LIMIT_BYTES,
  PROJECT_ENVELOPE_MANIFEST_LIMIT_BYTES,
  PROJECT_ENVELOPE_WRAPPED_KEY_BYTES,
  assertWriteCapacityAllowed,
  assessProjectWriteCapacity,
  computeBackupPayloadBytes,
  computeProjectedStoredBytes,
  estimateAvailableQuota,
  evaluateWriteCapacity,
  type AssessProjectWriteCapacityInput,
  type BackupPayloadPart,
  type EvaluateWriteCapacityInput,
  type QuotaEstimate,
  type WriteCapacityDecision,
  type WriteCapacityRejectionReason,
} from "./quota.js";
export {
  PROJECT_INDEX_DB_NAME,
  PROJECT_INDEX_DB_VERSION,
  PROJECT_OBJECTS_BY_TRANSACTION_INDEX,
  PROJECT_OBJECTS_STORE,
  PROJECT_TRANSACTIONS_STORE,
  openCommitIndexStore,
  type CommitIndexStore,
  type ProjectObjectRecord,
  type TransactionRecord,
} from "./commit-index.js";

export {
  PROJECT_OBJECTS_ROOT_DIR,
  PROJECT_OBJECTS_TRANSACTIONS_DIR,
  PROJECT_OBJECT_FILE_SUFFIX,
  openOpfsObjectStore,
  type OpfsObjectStore,
} from "./opfs.js";

export {
  PROJECT_OBJECT_AAD_KIND,
  commitProjectObjects,
  listCommittedObjectIds,
  openProjectObject,
  openProjectObjectStore,
  projectObjectPath,
  recoverProjectObjects,
  type CommitProjectObjectsInput,
  type CommitProjectObjectsResult,
  type OpenProjectObjectStoreInput,
  type ProjectObjectCoreDeps,
  type ProjectObjectInput,
  type ProjectObjectStore,
  type RecoveryResult,
} from "./project-object-store.js";