packages:
  - "apps/*"
  - "packages/*"
  - "services/*"

engineStrict: true
saveExact: true
strictPeerDependencies: true
autoInstallPeers: false
linkWorkspacePackages: false
sharedWorkspaceLockfile: true
