import { readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { delimiter, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const designPath = resolve(repositoryRoot, "DESIGN.md");
const baselinePath = resolve(repositoryRoot, "tests/design/design-warning-baseline.v1.json");
const generatedThemePath = resolve(repositoryRoot, "packages/themes/src/index.ts");

const expectedThemes = [
  { id: "deep-space-neon", label: "深空霓虹" },
  { id: "soft-glass", label: "玻璃柔光" },
  { id: "data-editorial", label: "数据编辑部" },
  { id: "enterprise-minimal", label: "企业极简" },
];

const expectedSemanticRoles = [
  "canvas",
  "surface",
  "surface-raised",
  "text",
  "text-secondary",
  "text-muted",
  "border",
  "control-border",
  "focus",
  "primary",
  "primary-hover",
  "on-primary",
  "on-danger",
  "secondary",
  "success",
  "warning",
  "danger",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "chart-6",
  "chart-7",
  "chart-8",
  "sequential-1",
  "sequential-2",
  "sequential-3",
  "sequential-4",
  "sequential-5",
  "diverging-negative",
  "diverging-negative-soft",
  "diverging-neutral",
  "diverging-positive-soft",
  "diverging-positive",
];

const expectedSpacingTokens = [
  "none",
  "xxs",
  "xs",
  "sm",
  "md",
  "lg",
  "xl",
  "2xl",
  "3xl",
  "4xl",
  "5xl",
];

const expectedRoundedTokens = ["none", "control", "card", "panel", "hero", "pill"];

const expectedTypographyTokens = [
  "display-xl",
  "display-lg",
  "display-md",
  "heading-lg",
  "heading-md",
  "heading-sm",
  "body-lg",
  "body-md",
  "body-sm",
  "label",
  "caption",
  "metric-xl",
  "metric-lg",
  "axis",
  "data-mono",
];

function normalizeNewlines(value) {
  return value.replaceAll("\r\n", "\n");
}

function removeSingleTrailingNewline(value) {
  const normalized = normalizeNewlines(value);
  return normalized.endsWith("\n") ? normalized.slice(0, -1) : normalized;
}

function readText(path) {
  return normalizeNewlines(readFileSync(path, "utf8"));
}

function readJson(path) {
  return JSON.parse(readText(path));
}

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function sorted(values) {
  return [...values].sort((left, right) => left.localeCompare(right, "en"));
}

function jsonEqual(left, right) {
  return JSON.stringify(left) === JSON.stringify(right);
}

function createCollector() {
  const assertions = [];

  return {
    assert(passed, code, subject, message, expected, actual) {
      assertions.push({ passed, code, subject, message, expected, actual });
    },
    result() {
      const failures = assertions
        .filter(({ passed }) => !passed)
        .map(({ passed: _passed, ...failure }) => failure);
      return {
        assertions: {
          executed: assertions.length,
          passed: assertions.length - failures.length,
          failed: failures.length,
          skipped: 0,
        },
        failures,
      };
    },
  };
}

function canonicalFinding(finding) {
  return {
    severity: finding.severity,
    rule: finding.rule ?? null,
    path: finding.path ?? null,
    message: finding.message,
  };
}

function canonicalFindings(findings) {
  return findings
    .map(canonicalFinding)
    .sort((left, right) => JSON.stringify(left).localeCompare(JSON.stringify(right), "en"));
}

function expandReviewedWarnings(baseline) {
  const warnings = [];
  for (const group of baseline.reviewedWarnings ?? []) {
    for (const path of group.paths ?? []) {
      const token = path.slice(path.lastIndexOf(".") + 1);
      warnings.push({
        severity: group.severity,
        rule: group.rule,
        path,
        message: group.message ?? group.messageTemplate?.replaceAll("{token}", token),
      });
    }
  }
  return canonicalFindings(warnings);
}

function difference(left, right) {
  const rightSet = new Set(right.map((value) => JSON.stringify(value)));
  return left.filter((value) => !rightSet.has(JSON.stringify(value)));
}

function renderStringArray(lines, declaration, values) {
  lines.push(`export const ${declaration} = [`);
  for (const value of values) {
    lines.push(`  ${JSON.stringify(value)},`);
  }
  lines.push("] as const;", "");
}

function renderStringRecord(lines, declaration, entries) {
  lines.push(`export const ${declaration} = {`);
  for (const [name, value] of entries) {
    lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(value)},`);
  }
  lines.push("} as const;", "");
}

function renderGeneratedThemes(resolvedThemes, designSystemVariables) {
  const lines = [
    "/**",
    " * Generated from the machine-readable `themes` extension in DESIGN.md.",
    " * Do not edit this file independently; run the repository design generator.",
    " */",
  ];

  renderStringArray(lines, "THEME_IDS", expectedThemes.map(({ id }) => id));
  lines.push('export type ThemeId = (typeof THEME_IDS)[number];', "");
  renderStringArray(
    lines,
    "THEME_SEMANTIC_VARIABLES",
    expectedSemanticRoles.map((role) => `--dp-${role}`),
  );
  lines.push(
    "export type ThemeSemanticVariable = (typeof THEME_SEMANTIC_VARIABLES)[number];",
    "",
    "export interface ThemeDefinition {",
    "  readonly label: string;",
    "  readonly variables: Readonly<Record<ThemeSemanticVariable, string>>;",
    "}",
    "",
    "export const THEMES = {",
  );

  for (const { id } of expectedThemes) {
    const theme = resolvedThemes.get(id);
    lines.push(`  ${JSON.stringify(id)}: {`);
    lines.push(`    label: ${JSON.stringify(theme?.label)},`);
    lines.push("    variables: {");
    for (const role of expectedSemanticRoles) {
      lines.push(`      ${JSON.stringify(`--dp-${role}`)}: ${JSON.stringify(theme?.colors.get(role))},`);
    }
    lines.push("    },", "  },");
  }

  lines.push("} as const satisfies Readonly<Record<ThemeId, ThemeDefinition>>;", "");
  renderStringRecord(lines, "DESIGN_SYSTEM_VARIABLES", designSystemVariables);
  lines.push(
    "export type DesignSystemVariable = keyof typeof DESIGN_SYSTEM_VARIABLES;",
    "",
  );
  return lines.join("\n");
}

function resolveDesignSystemVariables(report, collector) {
  const groups = [
    {
      collection: report.designSystem.spacing,
      expected: expectedSpacingTokens,
      label: "spacing",
      variablePrefix: "--dp-space-",
    },
    {
      collection: report.designSystem.rounded,
      expected: expectedRoundedTokens,
      label: "rounded",
      variablePrefix: "--dp-radius-",
    },
  ];
  const variables = [];

  for (const group of groups) {
    const actualIds = sorted(group.collection.keys());
    const expectedIds = sorted(group.expected);
    collector.assert(
      jsonEqual(actualIds, expectedIds),
      "DESIGN_TOKEN_ID_SET",
      `DESIGN.md#${group.label}`,
      `${group.label} Token 集合必须稳定并完整生成`,
      expectedIds,
      actualIds,
    );
    for (const id of group.expected) {
      const token = group.collection.get(id);
      const valid =
        isRecord(token) &&
        token.type === "dimension" &&
        typeof token.value === "number" &&
        Number.isFinite(token.value) &&
        typeof token.unit === "string" &&
        token.unit.length > 0;
      collector.assert(
        valid,
        "DESIGN_DIMENSION_TOKEN_INVALID",
        `DESIGN.md#${group.label}.${id}`,
        "尺寸 Token 必须解析为有限数值和显式单位",
        "finite dimension",
        token,
      );
      if (valid) {
        variables.push([`${group.variablePrefix}${id}`, `${token.value}${token.unit}`]);
      }
    }
  }

  const actualTypographyIds = sorted(report.designSystem.typography.keys());
  const expectedTypographyIds = sorted(expectedTypographyTokens);
  collector.assert(
    jsonEqual(actualTypographyIds, expectedTypographyIds),
    "DESIGN_TYPOGRAPHY_ID_SET",
    "DESIGN.md#typography",
    "Typography Token 集合必须稳定并完整生成",
    expectedTypographyIds,
    actualTypographyIds,
  );
  for (const id of expectedTypographyTokens) {
    const token = report.designSystem.typography.get(id);
    const fontSize = isRecord(token) ? token.fontSize : null;
    const valid =
      isRecord(token) &&
      token.type === "typography" &&
      typeof token.fontFamily === "string" &&
      token.fontFamily.length > 0 &&
      typeof token.fontWeight === "number" &&
      Number.isFinite(token.fontWeight) &&
      isRecord(fontSize) &&
      fontSize.type === "dimension" &&
      typeof fontSize.value === "number" &&
      Number.isFinite(fontSize.value) &&
      typeof fontSize.unit === "string" &&
      fontSize.unit.length > 0;
    collector.assert(
      valid,
      "DESIGN_TYPOGRAPHY_TOKEN_INVALID",
      `DESIGN.md#typography.${id}`,
      "Typography Token 必须解析为字体族、字重与显式字号",
      "resolved typography",
      token,
    );
    if (!valid) {
      continue;
    }
    variables.push([`--dp-font-family-${id}`, token.fontFamily]);
    variables.push([`--dp-font-size-${id}`, `${fontSize.value}${fontSize.unit}`]);
    variables.push([`--dp-font-weight-${id}`, String(token.fontWeight)]);

    const letterSpacing = token.letterSpacing;
    if (letterSpacing !== undefined) {
      const validLetterSpacing =
        isRecord(letterSpacing) &&
        letterSpacing.type === "dimension" &&
        typeof letterSpacing.value === "number" &&
        Number.isFinite(letterSpacing.value) &&
        typeof letterSpacing.unit === "string" &&
        letterSpacing.unit.length > 0;
      collector.assert(
        validLetterSpacing,
        "DESIGN_LETTER_SPACING_TOKEN_INVALID",
        `DESIGN.md#typography.${id}.letterSpacing`,
        "字距 Token 必须解析为有限数值和显式单位",
        "finite dimension",
        letterSpacing,
      );
      if (validLetterSpacing) {
        variables.push([
          `--dp-letter-spacing-${id}`,
          `${letterSpacing.value}${letterSpacing.unit}`,
        ]);
      }
    }
  }

  return variables;
}

function resolveThemes(report, collector) {
  const rawThemes = report.designSystem.unknownKeyValues?.themes;
  collector.assert(
    isRecord(rawThemes),
    "DESIGN_THEMES_EXTENSION_MISSING",
    "DESIGN.md#themes",
    "DESIGN.md 必须提供机器可读 themes 扩展",
    "object",
    rawThemes === null ? null : typeof rawThemes,
  );

  if (!isRecord(rawThemes)) {
    return new Map();
  }

  const actualThemeIds = sorted(Object.keys(rawThemes));
  const requiredThemeIds = sorted(expectedThemes.map(({ id }) => id));
  collector.assert(
    jsonEqual(actualThemeIds, requiredThemeIds),
    "DESIGN_THEME_ID_SET",
    "DESIGN.md#themes",
    "主题 ID 必须与冻结的四主题精确一致",
    requiredThemeIds,
    actualThemeIds,
  );

  const resolvedThemes = new Map();
  for (const expectedTheme of expectedThemes) {
    const rawTheme = rawThemes[expectedTheme.id];
    const subject = `DESIGN.md#themes.${expectedTheme.id}`;
    collector.assert(
      isRecord(rawTheme),
      "DESIGN_THEME_INVALID",
      subject,
      "每个主题必须是对象",
      "object",
      rawTheme === null ? null : typeof rawTheme,
    );
    if (!isRecord(rawTheme)) {
      continue;
    }

    collector.assert(
      jsonEqual(sorted(Object.keys(rawTheme)), ["label", "semanticColors"]),
      "DESIGN_THEME_PROPERTIES",
      subject,
      "主题只允许 label 与 semanticColors",
      ["label", "semanticColors"],
      sorted(Object.keys(rawTheme)),
    );
    collector.assert(
      rawTheme.label === expectedTheme.label,
      "DESIGN_THEME_LABEL",
      `${subject}.label`,
      "主题中文标签必须稳定",
      expectedTheme.label,
      rawTheme.label,
    );

    const rawColors = rawTheme.semanticColors;
    collector.assert(
      isRecord(rawColors),
      "DESIGN_THEME_COLORS_INVALID",
      `${subject}.semanticColors`,
      "semanticColors 必须是对象",
      "object",
      rawColors === null ? null : typeof rawColors,
    );
    if (!isRecord(rawColors)) {
      continue;
    }

    const actualRoles = sorted(Object.keys(rawColors));
    const requiredRoles = sorted(expectedSemanticRoles);
    collector.assert(
      jsonEqual(actualRoles, requiredRoles),
      "DESIGN_THEME_ROLE_SET",
      `${subject}.semanticColors`,
      "每个主题必须完整提供 35 个语义色角色",
      requiredRoles,
      actualRoles,
    );

    const colors = new Map();
    for (const role of expectedSemanticRoles) {
      const rawReference = rawColors[role];
      const referenceMatch =
        typeof rawReference === "string" ? /^\{(colors\.[a-zA-Z0-9._-]+)\}$/.exec(rawReference) : null;
      collector.assert(
        Boolean(referenceMatch),
        "DESIGN_THEME_REFERENCE",
        `${subject}.semanticColors.${role}`,
        "主题语义色只能引用 DESIGN.md colors Token，不接受字面色或其他组",
        "{colors.<token>}",
        rawReference,
      );
      if (!referenceMatch) {
        continue;
      }

      const referencePath = referenceMatch[1];
      const resolved = report.designSystem.symbolTable.get(referencePath);
      const isResolvedColor =
        isRecord(resolved) && resolved.type === "color" && typeof resolved.hex === "string";
      collector.assert(
        isResolvedColor,
        "DESIGN_THEME_REFERENCE_UNRESOLVED",
        `${subject}.semanticColors.${role}`,
        "主题引用必须解析为有效颜色",
        "resolved color",
        referencePath,
      );
      if (isResolvedColor) {
        colors.set(role, resolved.hex);
      }
    }

    if (colors.size === expectedSemanticRoles.length) {
      resolvedThemes.set(expectedTheme.id, { label: expectedTheme.label, colors });
    }
  }

  return resolvedThemes;
}

function evaluateDesign({
  content,
  baseline,
  generatedSource,
  lint,
  installedTool,
  cliVersion,
  rootPackage,
  skipGeneratedCheck = false,
}) {
  const collector = createCollector();

  collector.assert(
    baseline.schemaVersion === 1,
    "DESIGN_BASELINE_VERSION",
    "design-warning-baseline",
    "warning baseline schemaVersion 必须受支持",
    1,
    baseline.schemaVersion,
  );
  collector.assert(
    baseline.designFile === "DESIGN.md",
    "DESIGN_BASELINE_SOURCE",
    "design-warning-baseline",
    "warning baseline 必须绑定根 DESIGN.md",
    "DESIGN.md",
    baseline.designFile,
  );
  collector.assert(
    installedTool.name === baseline.tool?.package && installedTool.version === baseline.tool?.version,
    "DESIGN_CLI_VERSION",
    "@google/design.md",
    "实际安装的 Design CLI 必须与审查基线精确一致",
    baseline.tool,
    installedTool,
  );
  collector.assert(
    cliVersion.status === 0 &&
      cliVersion.stdout === baseline.tool?.version &&
      cliVersion.stderr === "" &&
      cliVersion.error === null,
    "DESIGN_CLI_BIN_VERSION",
    "designmd --version",
    "跨平台 Design CLI bin 必须可执行且输出精确匹配固定版本",
    { command: "designmd --version", status: 0, stdout: baseline.tool?.version, stderr: "", error: null },
    cliVersion,
  );
  collector.assert(
    rootPackage.devDependencies?.[baseline.tool?.package] === baseline.tool?.version,
    "DESIGN_ROOT_DEPENDENCY",
    "package.json#devDependencies",
    "根开发依赖必须精确固定 Design CLI 版本",
    baseline.tool?.version,
    rootPackage.devDependencies?.[baseline.tool?.package] ?? null,
  );

  let report;
  try {
    report = lint(content);
    collector.assert(
      true,
      "DESIGN_LINT_EXECUTION",
      "DESIGN.md",
      "Design linter 必须完成解析",
      "completed",
      "completed",
    );
  } catch (error) {
    collector.assert(
      false,
      "DESIGN_LINT_EXECUTION",
      "DESIGN.md",
      "Design linter 必须完成解析",
      "completed",
      error instanceof Error ? error.message : String(error),
    );
    const collected = collector.result();
    return {
      ...collected,
      result: "failed",
      lintSummary: null,
      resolvedThemes: new Map(),
      designSystemVariables: [],
      expectedGeneratedSource: null,
      generatedMatched: false,
    };
  }

  const errors = canonicalFindings(report.findings.filter(({ severity }) => severity === "error"));
  collector.assert(
    errors.length === 0,
    "DESIGN_LINT_ERRORS",
    "DESIGN.md",
    "任何 Design lint error 都必须阻断",
    [],
    errors,
  );

  const actualWarnings = canonicalFindings(
    report.findings.filter(({ severity }) => severity === "warning"),
  );
  const reviewedWarnings = expandReviewedWarnings(baseline);
  const addedWarnings = difference(actualWarnings, reviewedWarnings);
  const removedWarnings = difference(reviewedWarnings, actualWarnings);
  collector.assert(
    addedWarnings.length === 0 && removedWarnings.length === 0,
    "DESIGN_WARNING_BASELINE",
    "DESIGN.md",
    "warning 集合必须与逐项审查基线精确一致；新增或移除都要求显式更新",
    { added: [], removed: [] },
    { added: addedWarnings, removed: removedWarnings },
  );
  collector.assert(
    jsonEqual(report.summary, baseline.expectedSummary),
    "DESIGN_LINT_SUMMARY",
    "DESIGN.md",
    "lint 汇总必须与固定工具版本的审查结果一致",
    baseline.expectedSummary,
    report.summary,
  );

  const resolvedThemes = resolveThemes(report, collector);
  collector.assert(
    resolvedThemes.size === expectedThemes.length,
    "DESIGN_THEME_RESOLUTION",
    "DESIGN.md#themes",
    "四主题必须全部解析为完整语义色映射",
    expectedThemes.length,
    resolvedThemes.size,
  );

  const designSystemVariables = resolveDesignSystemVariables(report, collector);

  const expectedGeneratedSource =
    resolvedThemes.size === expectedThemes.length
      ? renderGeneratedThemes(resolvedThemes, designSystemVariables)
      : null;
  const generatedMatched =
    expectedGeneratedSource !== null && normalizeNewlines(generatedSource) === expectedGeneratedSource;
  if (!skipGeneratedCheck) {
    collector.assert(
      generatedMatched,
      "DESIGN_GENERATED_DRIFT",
      "packages/themes/src/index.ts",
      "提交的类型化主题映射必须与 DESIGN.md 的确定性生成结果一致",
      "generated source matches DESIGN.md",
      expectedGeneratedSource === null ? "theme resolution failed" : "generated source differs",
    );
  }

  const collected = collector.result();
  return {
    ...collected,
    result: collected.failures.length === 0 ? "passed" : "failed",
    lintSummary: report.summary,
    resolvedThemes,
    designSystemVariables,
    expectedGeneratedSource,
    generatedMatched,
  };
}

function replaceOnce(content, target, replacement) {
  const index = content.indexOf(target);
  if (index === -1) {
    throw new Error(`Self-test mutation target not found: ${target}`);
  }
  return `${content.slice(0, index)}${replacement}${content.slice(index + target.length)}`;
}

function runSelfTests(context) {
  const assertions = [];
  const expectFailureCode = (name, mutation, expectedCode) => {
    const result = evaluateDesign({ ...context, ...mutation });
    const actualCodes = result.failures.map(({ code }) => code);
    assertions.push({
      name,
      passed: result.result === "failed" && actualCodes.includes(expectedCode),
      expected: { result: "failed", code: expectedCode },
      actual: { result: result.result, codes: actualCodes },
    });
  };

  expectFailureCode(
    "恶意 CSS/代码样式色值被拒绝",
    {
      content: replaceOnce(
        context.content,
        '  primary: "#35D6F5"',
        '  primary: "javascript:alert(1)"',
      ),
    },
    "DESIGN_LINT_ERRORS",
  );
  expectFailureCode(
    "未审查 component warning 被拒绝",
    {
      content: replaceOnce(
        context.content,
        "  button-primary:\n",
        '  probe-unreviewed-warning:\n    borderColor: "{colors.primary}"\n  button-primary:\n',
      ),
    },
    "DESIGN_WARNING_BASELINE",
  );
  expectFailureCode(
    "缺失主题语义角色被拒绝",
    {
      content: replaceOnce(
        context.content,
        '      canvas: "{colors.canvas-dark}"\n',
        "",
      ),
    },
    "DESIGN_THEME_ROLE_SET",
  );
  expectFailureCode(
    "主题字面色绕过被拒绝",
    {
      content: replaceOnce(
        context.content,
        '      canvas: "{colors.canvas-dark}"',
        '      canvas: "#07111F"',
      ),
    },
    "DESIGN_THEME_REFERENCE",
  );
  expectFailureCode(
    "生成物漂移被拒绝",
    { generatedSource: `${context.generatedSource}// unreviewed drift\n` },
    "DESIGN_GENERATED_DRIFT",
  );

  const failures = assertions.filter(({ passed }) => !passed);
  return {
    result: failures.length === 0 ? "passed" : "failed",
    assertions: {
      executed: assertions.length,
      passed: assertions.length - failures.length,
      failed: failures.length,
      skipped: 0,
    },
    failures: failures.map(({ name, expected, actual }) => ({ name, expected, actual })),
  };
}

async function loadDesignTool() {
  const module = await import("@google/design.md/linter");
  const linterEntry = fileURLToPath(import.meta.resolve("@google/design.md/linter"));
  const manifest = readJson(resolve(dirname(linterEntry), "../../package.json"));
  return {
    lint: module.lint,
    manifest: { name: manifest.name, version: manifest.version },
  };
}

function readDesignCliVersion() {
  const pathKey = Object.keys(process.env).find((key) => key.toLowerCase() === "path") ?? "PATH";
  const env = { ...process.env };
  env[pathKey] = [resolve(repositoryRoot, "node_modules/.bin"), process.env[pathKey]]
    .filter(Boolean)
    .join(delimiter);
  const options = {
    cwd: repositoryRoot,
    encoding: "utf8",
    env,
    windowsHide: true,
  };
  const execution =
    process.platform === "win32"
      ? spawnSync("designmd --version", { ...options, shell: true })
      : spawnSync("designmd", ["--version"], options);

  return {
    command: "designmd --version",
    status: execution.status,
    stdout: removeSingleTrailingNewline(execution.stdout ?? ""),
    stderr: removeSingleTrailingNewline(execution.stderr ?? ""),
    error: execution.error instanceof Error ? execution.error.message : null,
  };
}

async function main() {
  const allowedArguments = new Set(["--self-test", "--write"]);
  const unknownArguments = process.argv.slice(2).filter((argument) => !allowedArguments.has(argument));
  if (unknownArguments.length > 0) {
    throw new Error(`Unknown arguments: ${unknownArguments.join(", ")}`);
  }

  const runSelfTest = process.argv.includes("--self-test");
  const writeGenerated = process.argv.includes("--write");
  const baseline = readJson(baselinePath);
  const rootPackage = readJson(resolve(repositoryRoot, "package.json"));
  const content = readText(designPath);
  const generatedSource = readText(generatedThemePath);
  const tool = await loadDesignTool();
  const cliVersion = readDesignCliVersion();
  const context = {
    content,
    baseline,
    generatedSource,
    lint: tool.lint,
    installedTool: tool.manifest,
    cliVersion,
    rootPackage,
  };

  const evaluation = evaluateDesign({ ...context, skipGeneratedCheck: writeGenerated });
  let wroteGenerated = false;
  if (writeGenerated && evaluation.result === "passed" && evaluation.expectedGeneratedSource !== null) {
    writeFileSync(generatedThemePath, evaluation.expectedGeneratedSource, "utf8");
    wroteGenerated = true;
  }

  const selfTest = runSelfTest
    ? runSelfTests({
        ...context,
        generatedSource: writeGenerated && wroteGenerated
          ? evaluation.expectedGeneratedSource
          : generatedSource,
      })
    : null;
  const result =
    evaluation.result === "passed" && (selfTest === null || selfTest.result === "passed")
      ? "passed"
      : "failed";
  const output = {
    schemaVersion: "1.0.0",
    kind: "datapulse-root-check-summary",
    check: "design-system",
    gateId: process.env.DATAPULSE_GATE_ID ?? null,
    runNonce: process.env.DATAPULSE_RUN_NONCE ?? null,
    result,
    platform: process.platform,
    architecture: process.arch,
    tool: tool.manifest,
    cli: cliVersion,
    lint: evaluation.lintSummary,
    themes: {
      expected: expectedThemes.length,
      resolved: evaluation.resolvedThemes.size,
      semanticRolesPerTheme: expectedSemanticRoles.length,
    },
    designTokens: {
      spacing: expectedSpacingTokens.length,
      rounded: expectedRoundedTokens.length,
      typography: expectedTypographyTokens.length,
      cssVariables: evaluation.designSystemVariables.length,
    },
    generated: {
      path: "packages/themes/src/index.ts",
      matched: wroteGenerated || evaluation.generatedMatched,
      wrote: wroteGenerated,
    },
    assertions: evaluation.assertions,
    selfTest,
    failures: evaluation.failures,
  };

  console.log(JSON.stringify(output, null, 2));
  if (result !== "passed") {
    process.exitCode = 1;
  }
}

try {
  await main();
} catch (error) {
  console.log(
    JSON.stringify(
      {
        schemaVersion: "1.0.0",
        kind: "datapulse-root-check-summary",
        check: "design-system",
        gateId: process.env.DATAPULSE_GATE_ID ?? null,
        runNonce: process.env.DATAPULSE_RUN_NONCE ?? null,
        result: "failed",
        platform: process.platform,
        architecture: process.arch,
        assertions: { executed: 1, passed: 0, failed: 1, skipped: 0 },
        selfTest: null,
        failures: [
          {
            code: "DESIGN_CHECK_EXCEPTION",
            subject: "design-check",
            message: "设计检查无法安全完成时必须 fail-closed",
            expected: "completed design check",
            actual: error instanceof Error ? error.message : String(error),
          },
        ],
      },
      null,
      2,
    ),
  );
  process.exitCode = 1;
}
